### PR TITLE
Leads bulk email invitation

### PR DESCRIPTION
**Pull request by EduBeghe**
- Added script to send invitation to all new leads
- Added all new due dates to DB
- Added bulk import sql script

### CODE REVIEW

**Comment by MichaelAshmead** [comment]
@EduBeghe Let's just make sure we don't upload the .XLSX files too b/c this is a public repo and we don't want to leak that kind of info

**Comment by MichaelAshmead** [comment]
@EduBeghe Can we also rename folder to be: `leads_import_script` just so it matches the formatting of other folders

**Comment by EduBeghe** [comment]
> @EduBeghe Let's just make sure we don't upload the .XLSX files too b/c this is a public repo and we don't want to leak that kind of info

Fixed

**Comment by EduBeghe** [comment]
> @EduBeghe Can we also rename folder to be: `leads_import_script` just so it matches the formatting of other folders

Fixed

**Review by MichaelAshmead — APPROVED** [review]

**Pull request merged**
